export const Data = {
  genres: [
    { _id: "5b21ca3eeb7f6fbccd471818", name: "HTML & CSS" },
    { _id: "5b21ca3eeb7f6fbccd471814", name: "JAVASCRIPT" },
    { _id: "5b21ca3eeb7f6fbccd471820", name: "REACT" },
    { _id: "5b21ca3eeb7f6fbccd471821", name: "FULL STACK" },
  ],

  projects: [
    {
      _id: "5b21ca3eeb7f6fbccd471815",
      title: "Project1",
      projectLink: "this is a javascript",
      gitLink: "this is a javascript",
      description: "this is a javascript",
      tools: ["Html ", " Css", " Javascript"],
      genre: { _id: "5b21ca3eeb7f6fbccd471814", name: "JAVASCRIPT" },
      publishDate: "2018-01-03T19:04:28.809Z",
      image: "mount.jpg",
    },
    {
      _id: "5b21ca3eeb7f6fbccd471815j",
      title: "Project2",
      projectLink: "this a pure html , css javascript project",
      gitLink: "this a pure html , css javascript project",
      description: "this a pure html , css javascript project",
      tools: ["Html ", " Css", " Javascript"],
      genre: { _id: "5b21ca3eeb7f6fbccd471814", name: "JAVASCRIPT" },
      publishDate: "2018-01-03T19:04:28.809Z",
      image: "1.jpg",
    },
    {
      _id: "5b21ca3eeb7f6fbccd47181",
      title: "Project3",
      projectLink: "this is a html and css project",
      gitLink: "this is a html and css project",
      description: "this is a html and css project",
      tools: ["Html ", " css"],
      genre: { _id: "5b21ca3eeb7f6fbccd471818", name: "HTML & CSS" },
      publishDate: "2018-01-03T19:04:28.809Z",
      image: "1.jpg",
    },
    {
      _id: "5b21ca3eeb7f6fbccd47181h",
      title: "Project4",
      projectLink: "this is a pure  html and css project",
      gitLink: "this is a pure  html and css project",
      description: "this is a pure  html and css project",
      tools: ["Html ", " css"],
      genre: { _id: "5b21ca3eeb7f6fbccd471818", name: "HTML & CSS" },
      publishDate: "2018-01-03T19:04:28.809Z",
      image: "1.jpg",
    },
    {
      _id: "5b21ca3eeb7f6fbccd4718",
      title: "Project5",
      projectLink: "this is a React Project",
      gitLink: "this is a React Project",
      description: "this is a React Project",
      tools: ["Html ", " css", " React"],
      genre: { _id: "5b21ca3eeb7f6fbccd471820", name: "REACT" },
      publishDate: "2018-01-03T19:04:28.809Z",
      image: "1.jpg",
    },
    {
      _id: "5b21ca3eeb7f6fbccd4718r",
      title: "Project6",
      projectLink: " React Eccomerce Project",
      gitLink: " React Eccomerce Project",
      description: " React Eccomerce Project",
      tools: ["Html ", " css ", "React"],
      genre: { _id: "5b21ca3eeb7f6fbccd471820", name: "REACT" },
      publishDate: "2018-01-03T19:04:28.809Z",
      image: "1.jpg",
    },
    {
      _id: "5b21ca3eeb7f6fbccd471",
      title: "Project7",
      projectLink: "this project is based on full developmemntReact ",
      gitLink: "this project is based on full developmemntReact ",
      description: "this project is based on full developmemntReact ",
      tools: ["Html ", " css ", " React ", " MongoDb ", " Node Js"],
      genre: { _id: "5b21ca3eeb7f6fbccd471821", name: "FULL STACK" },
      publishDate: "2018-01-03T19:04:28.809Z",
      image: "1.jpg",
    },
    {
      _id: "5b21ca3eeb7f6fbccd471f",
      title: "Project8",
      projectLink: "musiq player based on full developmemntReact ",
      gitLink: "musiq player based on full developmemntReact ",
      description: "musiq player based on full developmemntReact ",
      tools: ["Html ", " css ", " React ", " MongoDb ", " Node Js"],
      genre: { _id: "5b21ca3eeb7f6fbccd471821", name: "FULL STACK" },
      publishDate: "2018-01-03T19:04:28.809Z",
      image: "1.jpg",
    },
    {
      _id: "5b21ca3eeb7f6fbccd471fs",
      title: "Project9",
      projectLink: "chat app on full developmemnt React ",
      gitLink: "chat app on full developmemnt React ",
      description: "chat app on full developmemnt React ",
      tools: ["Html ", " css ", "React ", " MongoDb ", " Node Js"],
      genre: { _id: "5b21ca3eeb7f6fbccd471821", name: "FULL STACK" },
      publishDate: "2018-01-03T19:04:28.809Z",
      image: "1.jpg",
    },
  ],

  comments: [
    {
      id: 1,
      body: "some comment",
      postId: 1,
    },
  ],
};
